CREATE DATABASE QT;
CREATE TABLE QT.PNR (
EMP_ID INT,
 EMP_NAME VARCHAR(25),
 DESIGNATION VARCHAR(25),
 SALARY INT,
 CITY VARCHAR(25)
 );
 
 
DESC QT.PNR; 

ALTER TABLE TCS.EMPLOYEE;

SELECT * FROM QT.PNR;

SET SQL_SAFE_UPDATES = 0;

UPDATE QT.PNR
SET CITY = 'NELLORE'
WHERE EMP_ID = 104;

INSERT INTO QT.PNR VALUES (108, 'KRISH', 'HCU', 40000, NULL);

UPDATE QT.PNR SET DESIGNATION = 'ENGINEER' WHERE EMP_ID = 105;

SELECT DISTINCT EMP_ID FROM TCS.EMPLOYEE;

DELETE FROM TCS.EMPLOYEE WHERE EMP_ID = '1100';



 